language: emacs-lisp
sudo: required
dist: trusty
matrix:
  fast_finish: true
env:
  # - EMACS_VERSION=25.1
  # - EMACS_VERSION=25.2
  - EMACS_VERSION=25.3
   # - EMACS_VERSION=snapshot
before_install:
  - rm -rf ~/.emacs.d/eclipse.jdt.ls/
  - export PATH="$HOME/bin:$PATH"
  - wget 'https://raw.githubusercontent.com/flycheck/emacs-travis/master/emacs-travis.mk'
  - make -f emacs-travis.mk install_emacs
  - make -f emacs-travis.mk install_cask
install:
  - cask install
script:
  - cask exec ecukes --timeout 60 features/Breakpoints.feature features/JUnit.feature
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3c80316cc2101deff8ce
    on_success: change
    on_failure: always
    on_start: never
cache:
  directories:
  - $HOME/.m2
  - "$HOME/emacs/"
  - "$HOME/.emacs.d/"
