(package "treesit-fold"
         "0.2.1"
         "Code folding using Emacs 29+ builtin tree-sitter")

(website-url "https://github.com/abougouffa/treesit-fold")
(keywords "convenience" "folding" "tree-sitter")

(package-file "treesit-fold.el")
(files "treesit-*.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "melpa")

(depends-on "emacs" "26.1")
(depends-on "fringe-helper")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
